name: Diff Tree Demo

# Watch Policy branch
on:
  workflow_dispatch:
 # push:
  #  branches:
     # -  main

permissions:
  id-token: write
  contents: read

jobs:
  handle-policy:
    runs-on: [self-hosted]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 10
      - name: Git Exposure
        run: |
          printenv
          git diff-tree --no-commit-id --name-only -r $CI_COMMIT_SHORT_SHA